//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public int ADDRESS_ID { get; set; }
        public int CUSTOMER_ID { get; set; }
        public string ADDRESS1 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string POSTAL { get; set; }
        public string COUNTRY { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string EMAIL_SECOND { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<int> LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
    }
}
