//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class animal
    {
        public int ANIMAL_ID { get; set; }
        public string ANIMAL_NAME { get; set; }
        public int CUSTOMER_ID { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public string BREED_TYPE { get; set; }
        public string DEPARTMENT { get; set; }
        public string REGISTRY_NO { get; set; }
        public string SEX { get; set; }
        public string ANIMAL_IDENTIFICATION { get; set; }
        public string COLOR { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public string WEIGHT_CLASS { get; set; }
        public string NAME_OF_SIRE { get; set; }
        public string REGISTRY_NO_SIR { get; set; }
        public string NAME_OF_DAM { get; set; }
        public string REGISTRY_OF_DAM { get; set; }
        public Nullable<int> LOT_NUMBER { get; set; }
        public Nullable<int> ENTRY_NUMBER { get; set; }
        public string SELLER { get; set; }
        public Nullable<System.DateTime> PURCHASE_DATE { get; set; }
        public Nullable<decimal> COST_OF_HEIFER { get; set; }
        public Nullable<System.DateTime> SHEERING_DATE_OLD { get; set; }
        public Nullable<System.DateTime> SHEERING_DATE_NEW { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<int> LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public string ANIMAL_TYPE { get; set; }
    }
}
