//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class clfs_winner_info
    {
        public int Line_id { get; set; }
        public int SHOW_YEAR { get; set; }
        public int EXHIBITOR_ID { get; set; }
        public string EXHIBITOR_NUMBER { get; set; }
        public string EXHIBITOR_NAME { get; set; }
        public int CLFS_DONOR_ID { get; set; }
        public string DONOR_NUMBER { get; set; }
        public string DONOR_NAME { get; set; }
        public Nullable<int> ANIMAL_ID { get; set; }
        public string REGISTRATION_PAPERS { get; set; }
        public string MONTHLY_REPORT1 { get; set; }
        public string MONTHLY_REPORT2 { get; set; }
        public string MONTHLY_REPORT3 { get; set; }
        public string MONTHLY_REPORT4 { get; set; }
        public string MONTHLY_REPORT5 { get; set; }
        public string MONTHLY_REPORT6 { get; set; }
        public string MONTHLY_REPORT7 { get; set; }
        public string MONTHLY_REPORT8 { get; set; }
        public string MONTHLY_REPORT9 { get; set; }
        public string MONTHLY_REPORT10 { get; set; }
        public string MONTHLY_REPORT11 { get; set; }
        public string MONTHLY_REPORT12 { get; set; }
        public string BREED_ESSAY { get; set; }
        public string YEAR_END_ESSAY { get; set; }
        public string SCRAP_BOOK { get; set; }
        public string ASSESSMENT_INIT { get; set; }
        public string LEDGER_MONTH { get; set; }
        public string ASSESSMENT_FINAL { get; set; }
        public string COMMENTS { get; set; }
        public string CANCEL_FLAG { get; set; }
        public Nullable<System.DateTime> REG_PAPERS_RCVD_DATE { get; set; }
        public Nullable<System.DateTime> CERT_RCVD_DATE { get; set; }
        public Nullable<System.DateTime> SENT_TO_AP_DATE { get; set; }
        public Nullable<System.DateTime> MAILED_DATE { get; set; }
        public Nullable<int> NEW_CLUB_ID { get; set; }
        public Nullable<int> NEW_CONTACT_ID { get; set; }
        public string BREED_REPORT { get; set; }
        public string YEAR_END_REPORT { get; set; }
        public Nullable<System.DateTime> ASSESSMENT_INIT_SUBMIT_DATE { get; set; }
        public byte[] ASSESSMENT_INIT_BLOB { get; set; }
        public string ASSESSMENT_INIT_FILE_NAME { get; set; }
        public string ASSESSMENT_INIT_FILE_TYPE { get; set; }
        public Nullable<System.DateTime> LEDGER_MONTH_SUBMIT_DATE { get; set; }
        public byte[] LEDGER_MONTH_BLOB { get; set; }
        public string LEDGER_MONTH_FILE_NAME { get; set; }
        public string LEDGER_MONTH_FILE_TYPE { get; set; }
        public Nullable<System.DateTime> ASSESSMENT_FINAL_SUBMIT_DATE { get; set; }
        public byte[] ASSESSMENT_FINAL_BLOB { get; set; }
        public string ASSESSMENT_FINAL_FILE_NAME { get; set; }
        public string ASSESSMENT_FINAL_FILE_TYPE { get; set; }
        public Nullable<System.DateTime> BREED_RPT_SUBMIT_DATE { get; set; }
        public byte[] BREED_RPT_BLOB { get; set; }
        public string BREED_FILE_NAME { get; set; }
        public string BREED_FILE_TYPE { get; set; }
        public Nullable<System.DateTime> YREND_RPT_SUBMIT_DATE { get; set; }
        public byte[] YEAR_END_RPT_BLOB { get; set; }
        public string YREND_FILE_NAME { get; set; }
        public string YREND_FILE_TYPE { get; set; }
        public Nullable<int> DOCUMENT_ID_BRRPT { get; set; }
        public Nullable<int> DOCUMENT_ID_YERPT { get; set; }
        public Nullable<int> GREETER_CUST_ID { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<int> LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
    }
}
