//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class clfs_winner_monthly_documents
    {
        public int CLFS_DOC_ID { get; set; }
        public int HEADER_ID { get; set; }
        public byte[] PHOTO { get; set; }
        public string PHOTO_FILE_NAME { get; set; }
        public string PHOTO_FILE_TYPE { get; set; }
        public Nullable<System.DateTime> PHOTO_SUBMIT_DATE { get; set; }
        public Nullable<System.DateTime> PHOTO_END_DATE { get; set; }
        public byte[] CORRESPONDENCE { get; set; }
        public string CORR_FILE_NAME { get; set; }
        public string CORR_FILE_TYPE { get; set; }
        public Nullable<System.DateTime> CORR_SUBMIT_DATE { get; set; }
        public Nullable<System.DateTime> CORR_END_DATE { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<int> LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
    }
}
