//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CalfScramblerEntities : DbContext
    {
        public CalfScramblerEntities()
            : base("name=CalfScramblerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> addresses { get; set; }
        public virtual DbSet<animal> animals { get; set; }
        public virtual DbSet<clfs_winner_monthly_documents> clfs_winner_monthly_documents { get; set; }
        public virtual DbSet<clfs_winner_monthly_expenses> clfs_winner_monthly_expenses { get; set; }
        public virtual DbSet<clfs_winner_monthly_headers> clfs_winner_monthly_headers { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<clfs_authorization> clfs_authorization { get; set; }
        public virtual DbSet<clfs_winner_info> clfs_winner_info { get; set; }
    }
}
